name: FTP Deploy

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.rcmmultimedia.com  # Set this in GitHub repository secrets
          username: ${{ secrets.FTP_USERNAME }}  # Set this in GitHub repository secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Set this in GitHub repository secrets
          local-dir: './'  # Path to your HTML file and assets
